export { AuctionsWebService } from './AuctionsWebService';
export { AuctionsCreateHandler } from './AuctionsCreateHandler';
export { AuctionsRetrieveHandler } from './AuctionsRetrieveHandler';
export { AuctionsRetrieveByIdHandler } from './AuctionsRetrieveByIdHandler';
export { AuctionsUpdateByIdHandler } from './AuctionsUpdateByIdHandler';
export { AuctionsDeleteByIdHandler } from './AuctionsDeleteByIdHandler';
export { AuctionsCreateBetsHandler } from './AuctionsCreateBetsHandler';
export { AuctionsRetrieveBetsHandler } from './AuctionsRetrieveBetsHandler';
export { AuctionsRetrieveRecentHandler } from './AuctionsRetrieveRecentHandler';
